import type { MagazineArticle } from '@/lib/magazine/types'

export const ARTICLES_01: MagazineArticle[] = [
  {
    slug: 'editorial-why-europe-needs-a-standard',
    issue: 1,
    pillar: 'money',
    title: "Why Europe's Tech Market Needs a Standard",
    excerpt:
      'The European SaaS M&A market reached its highest recorded volume in 2026. Yet fragmentation and opacity persist. AEGRYN exists to change that — one certified asset at a time.',
    readingTimeMinutes: 4,
    seoKeywords: ['European tech M&A', 'SaaS certification', 'AEGRYN', 'CIFS protocol', 'tech M&A standard'],
    ctaTarget: 'grade',
    ctaLabel: 'Get your CIFS grade',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'market-european-tech-ma-2026-numbers',
    issue: 1,
    pillar: 'money',
    title: 'European Tech M&A — The 2026 Numbers',
    excerpt:
      '2,698 SaaS deals completed in 2025 — a record. EU M&A volume up +40% since 2023. Here is the data that defines the market we are operating in.',
    readingTimeMinutes: 6,
    seoKeywords: ['European SaaS M&A 2026', 'SaaS deal volume', 'EV/ARR multiples Europe', 'tech acquisition data', 'European discount'],
    ctaTarget: 'advisory',
    ctaLabel: 'Explore our advisory process',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'ai-recomposition-of-tech-value',
    issue: 1,
    pillar: 'ai',
    title: 'AI and the Recomposition of Tech Value',
    excerpt:
      '72% of SaaS M&A targets now reference AI. Median EV/Revenue for AI-native SaaS sits at 12.5x. But the premium is fragile — and the commoditisation trap is real.',
    readingTimeMinutes: 5,
    seoKeywords: ['AI SaaS valuation', 'AI M&A premium', 'EU AI Act M&A', 'AI-native SaaS multiples', 'proprietary data moat'],
    ctaTarget: 'grade',
    ctaLabel: 'Certify your AI asset',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'perspective-certification-table',
    issue: 1,
    pillar: 'build',
    title: 'What We See From the Certification Table',
    excerpt:
      'Less than 25% of submitted assets pass the CIFS certification threshold. Here is what the top 5 refusal reasons tell us about the state of European tech.',
    readingTimeMinutes: 7,
    seoKeywords: ['CIFS certification', 'tech asset certification', 'M&A readiness', 'due diligence Europe', 'asset grade'],
    ctaTarget: 'grade',
    ctaLabel: 'Start your certification',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'deal-watch-h1-2026',
    issue: 1,
    pillar: 'money',
    title: 'Deal Watch — Transactions That Shaped H1 2026',
    excerpt:
      'Five transactions from H1 2026 analysed through the CIFS lens. From Windsor.ai to OneStream — what worked, what did not, and what each grade would have signalled.',
    readingTimeMinutes: 8,
    seoKeywords: ['European tech deals 2026', 'SaaS acquisition analysis', 'M&A case study', 'Windsor AI acquisition', 'HealthTech deal'],
    ctaTarget: 'transaction',
    ctaLabel: 'List your asset on AEGRYN Transact',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'buyers-who-is-buying-european-tech',
    issue: 1,
    pillar: 'people',
    title: 'Who Is Buying European Tech in 2026',
    excerpt:
      'PE funds, search funds, strategic acquirers, family offices — four buyer profiles, four sets of criteria, and what each one actually looks for in a certified asset.',
    readingTimeMinutes: 5,
    seoKeywords: ['European tech buyers', 'PE lower mid-market', 'search fund ETA', 'strategic acquirer tech', 'family office SaaS'],
    ctaTarget: 'advisory',
    ctaLabel: 'Talk to our advisory team',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'outlook-2027-three-forces',
    issue: 1,
    pillar: 'build',
    title: 'Outlook 2027 — Three Forces Reshaping the Market',
    excerpt:
      'The EU AI Act enters into force. The founder succession wave accelerates. PE dry powder reaches record levels. Three structural forces that will define the next 12 months.',
    readingTimeMinutes: 5,
    seoKeywords: ['tech M&A outlook 2027', 'EU AI Act M&A impact', 'founder succession wave', 'PE dry powder Europe', 'SaaS market forecast'],
    ctaTarget: 'build',
    ctaLabel: 'Prepare your exit',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'aegryn-index-edition-1',
    issue: 1,
    pillar: 'build',
    title: 'AEGRYN Index — Edition 1, Proprietary Certification Data',
    excerpt:
      'Our certification database, made public for the first time. Acceptance rate, dimension scores, grade distribution — the baseline against which every future edition will be measured.',
    readingTimeMinutes: 3,
    seoKeywords: ['AEGRYN Index', 'CIFS certification data', 'tech asset grade distribution', 'certification acceptance rate', 'AEGRYN methodology'],
    ctaTarget: 'grade',
    ctaLabel: 'Get your AEGRYN grade',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'build-the-habit-that-changes-everything',
    issue: 1,
    pillar: 'build',
    title: 'The Habit That Changes Everything, Ten Years Later',
    excerpt:
      'He did not set out to build a company that would sell well. He set out to build one that would not embarrass him. A decade of small, boring, correct decisions — and why they mattered enormously.',
    readingTimeMinutes: 5,
    seoKeywords: ['build to sell', 'tech company preparation', 'data room clean', 'M&A readiness', 'European founder exit'],
    ctaTarget: 'grade',
    ctaLabel: 'Certify your asset',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'build-he-built-fast',
    issue: 1,
    pillar: 'build',
    title: 'He Built Fast. Then He Had to Slow Down and Check.',
    excerpt:
      'He built the first version of his product almost entirely with AI coding tools. A buyer\'s technical reviewer found something he had not thought to check. The fix took twelve weeks.',
    readingTimeMinutes: 4,
    seoKeywords: ['AI code review', 'technical due diligence', 'AI-generated code risk', 'tech asset audit', 'CIFS code review'],
    ctaTarget: 'grade',
    ctaLabel: 'Get a technical review',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'money-the-compliance-premium',
    issue: 1,
    pillar: 'money',
    title: 'The Buyers She Was Not Looking For',
    excerpt:
      'She had not planned to sell in 2026. A cold email from a compliance officer at a mid-sized Dutch bank changed her timeline — and her price. How DORA compliance created a premium she had not modelled.',
    readingTimeMinutes: 5,
    seoKeywords: ['DORA compliance M&A', 'RegTech acquisition', 'compliance premium', 'European tech sale', 'strategic acquirer'],
    ctaTarget: 'grade',
    ctaLabel: 'Certify your compliance posture',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'transaction-what-an-earnout-feels-like',
    issue: 1,
    pillar: 'money',
    title: 'What an Earn-Out Actually Feels Like',
    excerpt:
      'He sold his company for what looked like a good headline number. A third on closing, a third at month 12, a final third at month 24. What happened in between is the part nobody explains clearly.',
    readingTimeMinutes: 5,
    seoKeywords: ['earn-out structure', 'M&A earn-out risk', 'tech company sale earn-out', 'founder earn-out negotiation', 'European SaaS exit'],
    ctaTarget: 'transaction',
    ctaLabel: 'Talk to our transaction desk',
    publishedAt: '2027-01-01',
  },
  {
    slug: 'life-on-building-for-the-long-view',
    issue: 1,
    pillar: 'build',
    title: 'On Building for the Long View',
    excerpt:
      'The companies that sell well share one quality that has nothing to do with their product, their market, or their technology. It is a quality of attention.',
    readingTimeMinutes: 3,
    seoKeywords: ['building for exit', 'long-term founder mindset', 'European tech essay', 'deliberate founder', 'Aegryn point of view'],
    ctaTarget: 'build',
    ctaLabel: 'Prepare your exit',
    publishedAt: '2027-01-01',
  },
]
