import type { Pillar } from '@/lib/magazine/types'

/** Table des matieres de l'Issue 01, derivee de la web edition (elle-meme generee
    depuis le flipbook). Les ancres pointent dans aegryn-magazine-issue-01_web.html. */
export interface TocArticle { anchor: string; title: string; page: number }
export interface TocSection { id: string; label: string; pillar: Pillar; pageRange: string; articles: TocArticle[] }

export const TOC_01: TocSection[] = [
  { id: 's-opening', label: "Opening", pillar: 'build', pageRange: 'p.04–13', articles: [
    { anchor: 'the-aegryn-model-five-disciplines-one-st', title: "Five disciplines. One standard.", page: 4 },
    { anchor: 'sommaire-contents', title: "Contents", page: 5 },
    { anchor: 'masthead-aegryn', title: "Aegryn", page: 7 },
    { anchor: 'editorial-a-letter', title: "A Letter", page: 8 },
    { anchor: 'five-moments-in-the-life-of-a-company-ev', title: "Every company passes through the same five\u2026", page: 10 },
    { anchor: 'primer-five-words-worth-knowing', title: "Five Words Worth Knowing", page: 11 },
    { anchor: 'sources-how-we-know-what-we-say', title: "How We Know What We Say", page: 12 },
    { anchor: 'editorial-why-a-consulting-firm-publishes', title: "Why a Consulting Firm Publishes a Magazine", page: 13 },
  ] },
  { id: 's-tech-and-ai', label: "Tech and AI", pillar: 'ai', pageRange: 'p.14–40', articles: [
    { anchor: 'tech-and-ai-european-tech-certified-and-', title: "European tech. Certified and ready to\u2026", page: 14 },
    { anchor: 'tech-and-ai-founder-diary', title: "Founder Diary", page: 17 },
    { anchor: 'tech-and-ai-she-quit-on-a-tuesday', title: "She Quit on a Tuesday", page: 18 },
    { anchor: 'tech-and-ai-building-from-anywhere', title: "Building From Anywhere", page: 20 },
    { anchor: 'tech-and-ai-worth-knowing', title: "Worth Knowing", page: 24 },
    { anchor: 'tech-and-ai-the-tools', title: "The Tools", page: 25 },
    { anchor: 'tech-and-ai-what-actually-changed', title: "What Actually Changed", page: 26 },
    { anchor: 'tech-and-ai-one-page-of-reference', title: "One Page of Reference", page: 27 },
    { anchor: 'tech-and-ai-five-honest-lessons', title: "Five Honest Lessons", page: 28 },
    { anchor: 'dossier-the-back-office-goes-autonomous', title: "The Back Office Goes Autonomous", page: 30 },
    { anchor: 'dossier-what-the-data-says', title: "What the Data Says", page: 31 },
    { anchor: 'dossier-a-cfo-s-year-in-her-words', title: "A CFO's Year, in Her Words", page: 32 },
    { anchor: 'dossier-where-the-value-moves', title: "Where the Value Moves", page: 34 },
    { anchor: 'dossier-the-regulatory-clock', title: "The Regulatory Clock", page: 35 },
    { anchor: 'dossier-five-words-for-the-board', title: "Five Words for the Board", page: 36 },
    { anchor: 'dossier-what-to-do-on-monday', title: "What to Do on Monday", page: 37 },
    { anchor: 'advertising-subblink', title: "subblink. Clarity before commitment.", page: 40 },
  ] },
  { id: 's-build', label: "Build", pillar: 'build', pageRange: 'p.42–64', articles: [
    { anchor: 'build-field-notes', title: "Field Notes", page: 42 },
    { anchor: 'build-the-habit-that-changes-everything', title: "The Habit That Changes Everything", page: 43 },
    { anchor: 'build-30-the-typical-valuation-cut-for-a', title: "\u221230%: The typical valuation cut for a\u2026", page: 44 },
    { anchor: 'build-the-velocity-tax', title: "The Velocity Tax", page: 46 },
    { anchor: 'build-he-built-fast', title: "He Built Fast", page: 49 },
    { anchor: 'build-documented-before-built', title: "Documented Before Built", page: 50 },
    { anchor: 'build-point-of-view', title: "Point of View", page: 53 },
    { anchor: 'build-small-fix-big-save', title: "Small Fix, Big Save", page: 54 },
    { anchor: 'build-the-bookkeeper-who-saved-six-weeks', title: "The Bookkeeper Who Saved Six Weeks", page: 55 },
    { anchor: 'build-the-year-one-checklist', title: "The Year-One Checklist", page: 56 },
    { anchor: 'build-the-year-before', title: "The Year Before", page: 57 },
    { anchor: 'build-twelve-months-that-determine-the-p', title: "Twelve Months That Determine the Price", page: 59 },
    { anchor: 'build-the-long-goodbye', title: "The Long Goodbye", page: 60 },
    { anchor: 'build-he-had-twelve-months', title: "He Had Twelve Months", page: 61 },
    { anchor: 'build-the-three-documents', title: "The Three Documents", page: 62 },
    { anchor: 'build-the-art-of-the-data-room', title: "The Art of the Data Room", page: 64 },
  ] },
  { id: 's-money', label: "Money", pillar: 'money', pageRange: 'p.68–92', articles: [
    { anchor: 'money-before-you-read-on', title: "Before You Read On", page: 68 },
    { anchor: 'money-market-analysis', title: "Market Analysis", page: 70 },
    { anchor: 'money-market-analysis-the-chart', title: "Market Analysis, the Chart", page: 71 },
    { anchor: 'money-what-a-sale-actually-looks-like', title: "What a Sale Actually Looks Like", page: 72 },
    { anchor: 'money-what-buyers-actually-pay', title: "What Buyers Actually Pay", page: 76 },
    { anchor: 'money-the-geography-of-multiples', title: "The Geography of Multiples", page: 77 },
    { anchor: 'money-point-of-view', title: "Point of View", page: 78 },
    { anchor: 'money-no-investors-no-apology', title: "No Investors, No Apology", page: 79 },
    { anchor: 'money-the-bootstrap-path', title: "The Bootstrap Path", page: 80 },
    { anchor: 'money-the-investment-data', title: "The Investment Data", page: 82 },
    { anchor: 'money-the-metrics-that-move-the-number', title: "The Metrics That Move the Number", page: 83 },
    { anchor: 'money-the-unplanned-exit', title: "The Unplanned Exit", page: 84 },
    { anchor: 'money-the-compliance-premium', title: "The Compliance Premium", page: 85 },
    { anchor: 'money-the-compliance-premium-priced', title: "The Compliance Premium, Priced", page: 87 },
    { anchor: 'money-the-pivot-point', title: "The Pivot Point", page: 88 },
    { anchor: 'money-the-year-he-stopped-raising', title: "The Year He Stopped Raising", page: 90 },
    { anchor: 'money-what-the-emea-wave-means', title: "What the EMEA Wave Means", page: 92 },
  ] },
  { id: 's-portrait', label: "Portrait", pillar: 'money', pageRange: 'p.94–100', articles: [
    { anchor: 'portrait-the-first-capital', title: "The First Capital", page: 94 },
    { anchor: 'portrait-julien-guex-fit', title: "Julien Guex, FIT", page: 96 },
    { anchor: 'portrait-the-first-capital-in-numbers', title: "The First Capital, in Numbers", page: 100 },
  ] },
  { id: 's-value', label: "Value", pillar: 'money', pageRange: 'p.104–121', articles: [
    { anchor: 'value-deal-watch-2026', title: "Deal Watch 2026", page: 104 },
    { anchor: 'value-deal-01-and-02', title: "Deal 01 and 02", page: 105 },
    { anchor: 'value-deal-03-to-06', title: "Deal 03 to 06", page: 106 },
    { anchor: 'value-who-is-buying', title: "Who Is Buying", page: 108 },
    { anchor: 'value-the-process', title: "The Process", page: 109 },
    { anchor: 'value-getting-paid-later', title: "Getting Paid Later", page: 111 },
    { anchor: 'value-the-data-room', title: "The Data Room", page: 112 },
    { anchor: 'value-what-a-data-room-contains', title: "What a Data Room Contains", page: 114 },
    { anchor: 'value-inside-the-data-room', title: "Inside the Data Room", page: 115 },
    { anchor: 'value-first-48-hours', title: "First 48 Hours", page: 116 },
    { anchor: 'value-the-earn-out-story', title: "The Earn-Out Story", page: 117 },
    { anchor: 'value-the-aegryn-index', title: "The Aegryn Index", page: 118 },
    { anchor: 'value-aegryn-index-grade-distribution', title: "Aegryn Index, Grade Distribution", page: 119 },
    { anchor: 'value-where-first-submissions-fail', title: "Where First Submissions Fail", page: 120 },
    { anchor: 'value-point-of-view', title: "Point of View", page: 121 },
  ] },
  { id: 's-people', label: "People", pillar: 'people', pageRange: 'p.122–134', articles: [
    { anchor: 'people-who-you-will-meet', title: "Who You Will Meet", page: 122 },
    { anchor: 'people-the-first-leap', title: "The First Leap", page: 125 },
    { anchor: 'people-the-first-eighteen-months', title: "The First Eighteen Months", page: 127 },
    { anchor: 'people-years-two-to-five', title: "Years Two to Five", page: 128 },
    { anchor: 'people-the-second-try', title: "The Second Try", page: 129 },
    { anchor: 'people-what-the-restructuring-taught-the', title: "What the Restructuring Taught Them", page: 130 },
    { anchor: 'people-the-family-business', title: "The Family Business", page: 131 },
    { anchor: 'people-workshop-to-platform', title: "Workshop to Platform", page: 132 },
    { anchor: 'people-the-succession-wave-in-numbers', title: "The Succession Wave, in Numbers", page: 133 },
    { anchor: 'people-the-acquirer', title: "The Acquirer", page: 134 },
  ] },
  { id: 's-life', label: "Life", pillar: 'build', pageRange: 'p.136–146', articles: [
    { anchor: 'life-european-tech-cities', title: "European Tech Cities", page: 136 },
    { anchor: 'life-the-reading-list', title: "The Reading List", page: 139 },
    { anchor: 'life-essay', title: "Essay", page: 140 },
    { anchor: 'life-on-building-for-the-long-view', title: "On Building for the Long View", page: 142 },
    { anchor: 'life-the-founder-stack', title: "The Founder Stack", page: 143 },
    { anchor: 'life-quickfire', title: "Quickfire", page: 144 },
    { anchor: 'life-by-the-numbers', title: "By the Numbers", page: 145 },
    { anchor: 'life-the-charts', title: "The Charts", page: 146 },
  ] },
  { id: 's-closing', label: "Closing", pillar: 'build', pageRange: 'p.147–149', articles: [
    { anchor: 'closing-issue-02', title: "Issue 02", page: 147 },
    { anchor: 'closing-how-to-work-with-aegryn', title: "How to Work With Aegryn", page: 148 },
    { anchor: 'closing-why-aegryn-matters-to-advertiser', title: "Why Aegryn matters to advertisers.", page: 149 },
  ] },
]
