/**
 * Textes des accusés de réception, par formulaire et par langue.
 * Le visuel et les éléments communs (salutation, signature, pied) sont dans
 * lib/emailAck.ts ; ici uniquement ce qui change d'un formulaire à l'autre.
 */
import type { Lang } from '@/lib/emailAck'

type T = Record<Lang, Record<string, string>>

export const ACK: Record<string, T> = {

  /* ── Formulaire de contact standard ── */
  contact: {
    fr: { subject: 'Aegryn · Votre message est bien reçu', kicker: 'Message reçu', title: 'Nous avons bien reçu votre message', intro: 'Merci de nous avoir écrit. En voici le récapitulatif :', subjectLabel: 'Sujet', company: 'Société', message: 'Votre message', next: 'Un membre de l’équipe Aegryn prend connaissance de votre message et vous répond rapidement.' },
    en: { subject: 'Aegryn · Your message has been received', kicker: 'Message received', title: 'We have received your message', intro: 'Thank you for writing to us. Here is a summary:', subjectLabel: 'Subject', company: 'Company', message: 'Your message', next: 'A member of the Aegryn team is reading your message and will get back to you shortly.' },
    de: { subject: 'Aegryn · Ihre Nachricht ist eingegangen', kicker: 'Nachricht erhalten', title: 'Wir haben Ihre Nachricht erhalten', intro: 'Vielen Dank für Ihre Nachricht. Hier die Zusammenfassung:', subjectLabel: 'Betreff', company: 'Unternehmen', message: 'Ihre Nachricht', next: 'Ein Mitglied des Aegryn-Teams liest Ihre Nachricht und meldet sich in Kürze bei Ihnen.' },
    it: { subject: 'Aegryn · Il vostro messaggio è stato ricevuto', kicker: 'Messaggio ricevuto', title: 'Abbiamo ricevuto il vostro messaggio', intro: 'Grazie per averci scritto. Ecco il riepilogo:', subjectLabel: 'Oggetto', company: 'Società', message: 'Il vostro messaggio', next: 'Un membro del team Aegryn legge il vostro messaggio e vi risponderà a breve.' },
    es: { subject: 'Aegryn · Hemos recibido su mensaje', kicker: 'Mensaje recibido', title: 'Hemos recibido su mensaje', intro: 'Gracias por escribirnos. Este es el resumen:', subjectLabel: 'Asunto', company: 'Empresa', message: 'Su mensaje', next: 'Un miembro del equipo Aegryn está leyendo su mensaje y le responderá en breve.' },
    nl: { subject: 'Aegryn · Uw bericht is ontvangen', kicker: 'Bericht ontvangen', title: 'Wij hebben uw bericht ontvangen', intro: 'Bedankt voor uw bericht. Hier is de samenvatting:', subjectLabel: 'Onderwerp', company: 'Bedrijf', message: 'Uw bericht', next: 'Een lid van het Aegryn-team leest uw bericht en neemt binnenkort contact met u op.' },
  },

  /* ── Demande de certification CIFSO 5000 (/grade/submit) ── */
  certification: {
    fr: { subject: 'Aegryn · Votre demande de certification CIFSO 5000 est bien reçue', kicker: 'Demande reçue', title: 'Certification CIFSO 5000', intro: 'Nous avons bien reçu votre demande de certification. En voici le récapitulatif :', org: 'Organisation', pack: 'Forfait', objective: 'Objectif', size: 'Effectif', country: 'Pays', next: 'Notre équipe examine votre dossier et vous propose un pré-screening confidentiel. Les conditions définitives sont transmises après pré-qualification.', nda: 'Un accord de confidentialité vous sera proposé avant tout échange de documents.' },
    en: { subject: 'Aegryn · Your CIFSO 5000 certification request has been received', kicker: 'Request received', title: 'CIFSO 5000 Certification', intro: 'We have received your certification request. Here is a summary:', org: 'Organisation', pack: 'Package', objective: 'Objective', size: 'Headcount', country: 'Country', next: 'Our team is reviewing your file and will propose a confidential pre-screening. Final terms follow pre-qualification.', nda: 'A non-disclosure agreement will be offered before any exchange of documents.' },
    de: { subject: 'Aegryn · Ihre Anfrage zur CIFSO 5000-Zertifizierung ist eingegangen', kicker: 'Anfrage erhalten', title: 'CIFSO 5000-Zertifizierung', intro: 'Wir haben Ihre Zertifizierungsanfrage erhalten. Hier die Zusammenfassung:', org: 'Organisation', pack: 'Paket', objective: 'Ziel', size: 'Mitarbeitende', country: 'Land', next: 'Unser Team prüft Ihr Dossier und schlägt Ihnen ein vertrauliches Pre-Screening vor. Die definitiven Konditionen folgen nach der Vorqualifikation.', nda: 'Vor jedem Dokumentenaustausch wird Ihnen eine Vertraulichkeitsvereinbarung angeboten.' },
    it: { subject: 'Aegryn · La vostra richiesta di certificazione CIFSO 5000 è stata ricevuta', kicker: 'Richiesta ricevuta', title: 'Certificazione CIFSO 5000', intro: 'Abbiamo ricevuto la vostra richiesta di certificazione. Ecco il riepilogo:', org: 'Organizzazione', pack: 'Pacchetto', objective: 'Obiettivo', size: 'Organico', country: 'Paese', next: 'Il nostro team esamina il vostro dossier e vi propone un pre-screening riservato. Le condizioni definitive seguono la pre-qualifica.', nda: 'Un accordo di riservatezza vi sarà proposto prima di qualsiasi scambio di documenti.' },
    es: { subject: 'Aegryn · Hemos recibido su solicitud de certificación CIFSO 5000', kicker: 'Solicitud recibida', title: 'Certificación CIFSO 5000', intro: 'Hemos recibido su solicitud de certificación. Este es el resumen:', org: 'Organización', pack: 'Paquete', objective: 'Objetivo', size: 'Plantilla', country: 'País', next: 'Nuestro equipo revisa su expediente y le propondrá un pre-screening confidencial. Las condiciones definitivas se comunican tras la precalificación.', nda: 'Se le propondrá un acuerdo de confidencialidad antes de cualquier intercambio de documentos.' },
    nl: { subject: 'Aegryn · Uw aanvraag voor CIFSO 5000-certificering is ontvangen', kicker: 'Aanvraag ontvangen', title: 'CIFSO 5000-certificering', intro: 'Wij hebben uw certificeringsaanvraag ontvangen. Hier is de samenvatting:', org: 'Organisatie', pack: 'Pakket', objective: 'Doel', size: 'Personeelsbestand', country: 'Land', next: 'Ons team bekijkt uw dossier en stelt u een vertrouwelijke pre-screening voor. De definitieve voorwaarden volgen na de prekwalificatie.', nda: 'Vóór elke uitwisseling van documenten wordt u een geheimhoudingsovereenkomst voorgesteld.' },
  },

  /* ── Candidature partenariat (/alliances) ── */
  alliance: {
    fr: { subject: 'Aegryn · Votre candidature de partenariat est bien reçue', kicker: 'Candidature reçue', title: 'Partenariat Aegryn', intro: 'Nous avons bien reçu votre candidature. En voici le récapitulatif :', org: 'Organisation', type: 'Type de partenariat', country: 'Pays', next: 'Nos équipes examinent votre dossier et vous contactent pour un entretien de qualification.' },
    en: { subject: 'Aegryn · Your partnership application has been received', kicker: 'Application received', title: 'Aegryn Partnership', intro: 'We have received your application. Here is a summary:', org: 'Organisation', type: 'Partnership type', country: 'Country', next: 'Our teams are reviewing your file and will contact you for a qualification interview.' },
    de: { subject: 'Aegryn · Ihre Partnerschaftsbewerbung ist eingegangen', kicker: 'Bewerbung erhalten', title: 'Aegryn-Partnerschaft', intro: 'Wir haben Ihre Bewerbung erhalten. Hier die Zusammenfassung:', org: 'Organisation', type: 'Art der Partnerschaft', country: 'Land', next: 'Unsere Teams prüfen Ihr Dossier und kontaktieren Sie für ein Qualifikationsgespräch.' },
    it: { subject: 'Aegryn · La vostra candidatura di partenariato è stata ricevuta', kicker: 'Candidatura ricevuta', title: 'Partenariato Aegryn', intro: 'Abbiamo ricevuto la vostra candidatura. Ecco il riepilogo:', org: 'Organizzazione', type: 'Tipo di partenariato', country: 'Paese', next: 'I nostri team esaminano il vostro dossier e vi contattano per un colloquio di qualifica.' },
    es: { subject: 'Aegryn · Hemos recibido su candidatura de asociación', kicker: 'Candidatura recibida', title: 'Asociación Aegryn', intro: 'Hemos recibido su candidatura. Este es el resumen:', org: 'Organización', type: 'Tipo de asociación', country: 'País', next: 'Nuestros equipos revisan su expediente y le contactarán para una entrevista de calificación.' },
    nl: { subject: 'Aegryn · Uw partnerschapsaanvraag is ontvangen', kicker: 'Aanvraag ontvangen', title: 'Aegryn-partnerschap', intro: 'Wij hebben uw aanvraag ontvangen. Hier is de samenvatting:', org: 'Organisatie', type: 'Type partnerschap', country: 'Land', next: 'Onze teams bekijken uw dossier en nemen contact met u op voor een kwalificatiegesprek.' },
  },

  /* ── Candidature réseau d'experts (/experts) ── */
  expert: {
    fr: { subject: 'Aegryn · Votre candidature au réseau d’experts est bien reçue', kicker: 'Candidature reçue', title: 'Réseau d’experts Aegryn', intro: 'Votre candidature au réseau d’experts a bien été reçue. En voici le récapitulatif :', profile: 'Profil', org: 'Organisation', next: 'Nos équipes examinent votre dossier et vous contactent pour un entretien de qualification.', fee: 'L’accès au réseau se fait via un abonnement mensuel de référencement (89 CHF HT par mois).' },
    en: { subject: 'Aegryn · Your expert network application has been received', kicker: 'Application received', title: 'Aegryn Expert Network', intro: 'Your application to the expert network has been received. Here is a summary:', profile: 'Profile', org: 'Organisation', next: 'Our teams are reviewing your file and will contact you for a qualification interview.', fee: 'Access to the network is through a monthly listing subscription (CHF 89 excl. VAT per month).' },
    de: { subject: 'Aegryn · Ihre Bewerbung für das Expertennetzwerk ist eingegangen', kicker: 'Bewerbung erhalten', title: 'Aegryn-Expertennetzwerk', intro: 'Ihre Bewerbung für das Expertennetzwerk ist eingegangen. Hier die Zusammenfassung:', profile: 'Profil', org: 'Organisation', next: 'Unsere Teams prüfen Ihr Dossier und kontaktieren Sie für ein Qualifikationsgespräch.', fee: 'Der Zugang zum Netzwerk erfolgt über ein monatliches Listing-Abonnement (CHF 89 exkl. MwSt. pro Monat).' },
    it: { subject: 'Aegryn · La vostra candidatura alla rete di esperti è stata ricevuta', kicker: 'Candidatura ricevuta', title: 'Rete di esperti Aegryn', intro: 'La vostra candidatura alla rete di esperti è stata ricevuta. Ecco il riepilogo:', profile: 'Profilo', org: 'Organizzazione', next: 'I nostri team esaminano il vostro dossier e vi contattano per un colloquio di qualifica.', fee: 'L’accesso alla rete avviene tramite un abbonamento mensile di referenziamento (CHF 89 IVA esclusa al mese).' },
    es: { subject: 'Aegryn · Hemos recibido su candidatura a la red de expertos', kicker: 'Candidatura recibida', title: 'Red de expertos Aegryn', intro: 'Hemos recibido su candidatura a la red de expertos. Este es el resumen:', profile: 'Perfil', org: 'Organización', next: 'Nuestros equipos revisan su expediente y le contactarán para una entrevista de calificación.', fee: 'El acceso a la red se realiza mediante una suscripción mensual de referenciación (89 CHF sin IVA al mes).' },
    nl: { subject: 'Aegryn · Uw aanvraag voor het expertnetwerk is ontvangen', kicker: 'Aanvraag ontvangen', title: 'Aegryn-expertnetwerk', intro: 'Uw aanvraag voor het expertnetwerk is ontvangen. Hier is de samenvatting:', profile: 'Profiel', org: 'Organisatie', next: 'Onze teams bekijken uw dossier en nemen contact met u op voor een kwalificatiegesprek.', fee: 'Toegang tot het netwerk verloopt via een maandelijks vermeldingsabonnement (CHF 89 excl. btw per maand).' },
  },

  /* ── Estimation en ligne (/valuation) ── */
  valuation: {
    fr: { subject: 'Aegryn · Votre estimation indicative', kicker: 'Estimation reçue', title: 'Votre estimation indicative', intro: 'Voici le résultat de votre estimation en ligne et le détail de votre score :', grade: 'Grade estimé', score: 'Score', industry: 'Secteur', range: 'Fourchette indicative', disclaimer: 'Cette estimation est indicative, générée par algorithme à partir de vos données déclarées, sans vérification. Elle ne constitue pas un grade Aegryn officiel.', cta: 'Démarrer une certification officielle' },
    en: { subject: 'Aegryn · Your indicative estimate', kicker: 'Estimate received', title: 'Your indicative estimate', intro: 'Here is the result of your online estimate and the detail of your score:', grade: 'Estimated grade', score: 'Score', industry: 'Sector', range: 'Indicative range', disclaimer: 'This estimate is indicative, generated by algorithm from your declared data, without verification. It does not constitute an official Aegryn grade.', cta: 'Start an official certification' },
    de: { subject: 'Aegryn · Ihre indikative Schätzung', kicker: 'Schätzung erhalten', title: 'Ihre indikative Schätzung', intro: 'Hier das Ergebnis Ihrer Online-Schätzung und die Details Ihres Scores:', grade: 'Geschätzter Grade', score: 'Score', industry: 'Branche', range: 'Indikative Spanne', disclaimer: 'Diese Schätzung ist indikativ, algorithmisch aus Ihren Angaben erzeugt, ohne Prüfung. Sie stellt keinen offiziellen Aegryn-Grade dar.', cta: 'Offizielle Zertifizierung starten' },
    it: { subject: 'Aegryn · La vostra stima indicativa', kicker: 'Stima ricevuta', title: 'La vostra stima indicativa', intro: 'Ecco il risultato della vostra stima online e il dettaglio del punteggio:', grade: 'Grade stimato', score: 'Punteggio', industry: 'Settore', range: 'Intervallo indicativo', disclaimer: 'Questa stima è indicativa, generata da un algoritmo a partire dai dati dichiarati, senza verifica. Non costituisce un grade Aegryn ufficiale.', cta: 'Avviare una certificazione ufficiale' },
    es: { subject: 'Aegryn · Su estimación indicativa', kicker: 'Estimación recibida', title: 'Su estimación indicativa', intro: 'Este es el resultado de su estimación en línea y el detalle de su puntuación:', grade: 'Grado estimado', score: 'Puntuación', industry: 'Sector', range: 'Rango indicativo', disclaimer: 'Esta estimación es indicativa, generada por algoritmo a partir de los datos declarados, sin verificación. No constituye un grado Aegryn oficial.', cta: 'Iniciar una certificación oficial' },
    nl: { subject: 'Aegryn · Uw indicatieve schatting', kicker: 'Schatting ontvangen', title: 'Uw indicatieve schatting', intro: 'Hier is het resultaat van uw online schatting en het detail van uw score:', grade: 'Geschatte grade', score: 'Score', industry: 'Sector', range: 'Indicatieve bandbreedte', disclaimer: 'Deze schatting is indicatief, algoritmisch gegenereerd op basis van uw opgegeven gegevens, zonder verificatie. Ze vormt geen officiële Aegryn-grade.', cta: 'Een officiële certificering starten' },
  },

  /* ── Liste d'intérêt édition papier du magazine ── */
  printWishlist: {
    fr: { subject: 'Aegryn Magazine · Votre intérêt pour l’édition papier est enregistré', kicker: 'Intérêt enregistré', title: 'Édition papier du magazine', intro: 'Nous avons bien enregistré votre intérêt pour l’édition papier. En voici le récapitulatif :', interests: 'Centres d’intérêt', company: 'Entreprise', next: 'Nous vous contacterons lors du lancement de la production.' },
    en: { subject: 'Aegryn Magazine · Your interest in the print edition is registered', kicker: 'Interest registered', title: 'Print edition of the magazine', intro: 'We have registered your interest in the print edition. Here is a summary:', interests: 'Interests', company: 'Company', next: 'We will contact you when production launches.' },
    de: { subject: 'Aegryn Magazine · Ihr Interesse an der Printausgabe ist vorgemerkt', kicker: 'Interesse vorgemerkt', title: 'Printausgabe des Magazins', intro: 'Wir haben Ihr Interesse an der Printausgabe vorgemerkt. Hier die Zusammenfassung:', interests: 'Interessen', company: 'Unternehmen', next: 'Wir kontaktieren Sie beim Produktionsstart.' },
    it: { subject: 'Aegryn Magazine · Il vostro interesse per l’edizione cartacea è registrato', kicker: 'Interesse registrato', title: 'Edizione cartacea della rivista', intro: 'Abbiamo registrato il vostro interesse per l’edizione cartacea. Ecco il riepilogo:', interests: 'Interessi', company: 'Azienda', next: 'Vi contatteremo all’avvio della produzione.' },
    es: { subject: 'Aegryn Magazine · Su interés por la edición impresa está registrado', kicker: 'Interés registrado', title: 'Edición impresa de la revista', intro: 'Hemos registrado su interés por la edición impresa. Este es el resumen:', interests: 'Intereses', company: 'Empresa', next: 'Le contactaremos cuando se lance la producción.' },
    nl: { subject: 'Aegryn Magazine · Uw interesse in de gedrukte editie is geregistreerd', kicker: 'Interesse geregistreerd', title: 'Gedrukte editie van het magazine', intro: 'Wij hebben uw interesse in de gedrukte editie geregistreerd. Hier is de samenvatting:', interests: 'Interesses', company: 'Bedrijf', next: 'Wij nemen contact met u op bij de start van de productie.' },
  },

  /* ── Newsletter ── */
  newsletter: {
    fr: { subject: 'Aegryn · Vous êtes inscrit(e)', kicker: 'Inscription confirmée', title: 'Newsletter Built to Last', intro: 'Votre inscription est confirmée. Vous recevrez :', item1: 'Articles et analyses : marché, M&A, technologie, cycles de vie des organisations', item2: 'Aegryn Magazine : chaque numéro trimestriel dès parution', next: 'Une lettre, pas de prospection. Désabonnement en un clic à tout moment.', unsubscribe: 'Se désabonner' },
    en: { subject: 'Aegryn · You are subscribed', kicker: 'Subscription confirmed', title: 'Built to Last newsletter', intro: 'Your subscription is confirmed. You will receive:', item1: 'Articles and analysis: markets, M&A, technology, company lifecycles', item2: 'Aegryn Magazine: each quarterly issue on release', next: 'One letter, no prospecting. Unsubscribe in one click at any time.', unsubscribe: 'Unsubscribe' },
    de: { subject: 'Aegryn · Sie sind angemeldet', kicker: 'Anmeldung bestätigt', title: 'Newsletter Built to Last', intro: 'Ihre Anmeldung ist bestätigt. Sie erhalten:', item1: 'Artikel und Analysen: Markt, M&A, Technologie, Lebenszyklen von Unternehmen', item2: 'Aegryn Magazine: jede Quartalsausgabe bei Erscheinen', next: 'Ein Brief, keine Akquise. Abmeldung jederzeit mit einem Klick.', unsubscribe: 'Abmelden' },
    it: { subject: 'Aegryn · Siete iscritti', kicker: 'Iscrizione confermata', title: 'Newsletter Built to Last', intro: 'La vostra iscrizione è confermata. Riceverete:', item1: 'Articoli e analisi: mercato, M&A, tecnologia, cicli di vita delle organizzazioni', item2: 'Aegryn Magazine: ogni numero trimestrale all’uscita', next: 'Una lettera, nessuna prospezione. Disiscrizione in un clic in qualsiasi momento.', unsubscribe: 'Disiscriversi' },
    es: { subject: 'Aegryn · Está suscrito', kicker: 'Suscripción confirmada', title: 'Boletín Built to Last', intro: 'Su suscripción está confirmada. Recibirá:', item1: 'Artículos y análisis: mercado, M&A, tecnología, ciclos de vida de las organizaciones', item2: 'Aegryn Magazine: cada número trimestral al publicarse', next: 'Una carta, sin prospección. Baja en un clic en cualquier momento.', unsubscribe: 'Darse de baja' },
    nl: { subject: 'Aegryn · U bent ingeschreven', kicker: 'Inschrijving bevestigd', title: 'Nieuwsbrief Built to Last', intro: 'Uw inschrijving is bevestigd. U ontvangt:', item1: 'Artikelen en analyses: markt, M&A, technologie, levenscycli van organisaties', item2: 'Aegryn Magazine: elk kwartaalnummer bij verschijning', next: 'Eén brief, geen prospectie. Uitschrijven met één klik, op elk moment.', unsubscribe: 'Uitschrijven' },
  },

  /* ── Talent : candidature ── */
  talentCandidate: {
    fr: { subject: 'Aegryn Talent · Votre candidature est enregistrée', kicker: 'Candidature enregistrée', title: 'Aegryn Talent', intro: 'Nous avons bien reçu votre candidature. En voici le récapitulatif :', availability: 'Disponibilité', linkedin: 'LinkedIn', next: 'Notre équipe examine votre profil. S’il correspond à l’un de nos mandats de recrutement actifs, nous vous contactons pour un entretien de qualification, puis une présentation aux entreprises qui recrutent.', confidential: 'Votre recherche reste strictement confidentielle : nous ne partageons votre profil qu’avec votre accord explicite. Conformément au RGPD et à la LPD, vous pouvez demander la suppression de vos données à tout moment.' },
    en: { subject: 'Aegryn Talent · Your application is registered', kicker: 'Application registered', title: 'Aegryn Talent', intro: 'We have received your application. Here is a summary:', availability: 'Availability', linkedin: 'LinkedIn', next: 'Our team is reviewing your profile. If it matches one of our active recruitment mandates, we will contact you for a qualification interview, then introduce you to recruiting companies.', confidential: 'Your search remains strictly confidential: we only share your profile with your explicit consent. In accordance with GDPR and the Swiss FADP, you can request deletion of your data at any time.' },
    de: { subject: 'Aegryn Talent · Ihre Bewerbung ist erfasst', kicker: 'Bewerbung erfasst', title: 'Aegryn Talent', intro: 'Wir haben Ihre Bewerbung erhalten. Hier die Zusammenfassung:', availability: 'Verfügbarkeit', linkedin: 'LinkedIn', next: 'Unser Team prüft Ihr Profil. Passt es zu einem unserer aktiven Rekrutierungsmandate, kontaktieren wir Sie für ein Qualifikationsgespräch und stellen Sie anschliessend den rekrutierenden Unternehmen vor.', confidential: 'Ihre Suche bleibt streng vertraulich: Wir teilen Ihr Profil nur mit Ihrer ausdrücklichen Zustimmung. Gemäss DSGVO und DSG können Sie jederzeit die Löschung Ihrer Daten verlangen.' },
    it: { subject: 'Aegryn Talent · La vostra candidatura è registrata', kicker: 'Candidatura registrata', title: 'Aegryn Talent', intro: 'Abbiamo ricevuto la vostra candidatura. Ecco il riepilogo:', availability: 'Disponibilità', linkedin: 'LinkedIn', next: 'Il nostro team esamina il vostro profilo. Se corrisponde a uno dei nostri mandati di ricerca attivi, vi contattiamo per un colloquio di qualifica e poi vi presentiamo alle aziende che assumono.', confidential: 'La vostra ricerca resta strettamente riservata: condividiamo il vostro profilo solo con il vostro consenso esplicito. Ai sensi del GDPR e della LPD, potete chiedere la cancellazione dei vostri dati in qualsiasi momento.' },
    es: { subject: 'Aegryn Talent · Su candidatura está registrada', kicker: 'Candidatura registrada', title: 'Aegryn Talent', intro: 'Hemos recibido su candidatura. Este es el resumen:', availability: 'Disponibilidad', linkedin: 'LinkedIn', next: 'Nuestro equipo revisa su perfil. Si coincide con uno de nuestros mandatos de selección activos, le contactaremos para una entrevista de calificación y después le presentaremos a las empresas que contratan.', confidential: 'Su búsqueda es estrictamente confidencial: solo compartimos su perfil con su consentimiento explícito. Conforme al RGPD y a la LPD, puede solicitar la supresión de sus datos en cualquier momento.' },
    nl: { subject: 'Aegryn Talent · Uw sollicitatie is geregistreerd', kicker: 'Sollicitatie geregistreerd', title: 'Aegryn Talent', intro: 'Wij hebben uw sollicitatie ontvangen. Hier is de samenvatting:', availability: 'Beschikbaarheid', linkedin: 'LinkedIn', next: 'Ons team bekijkt uw profiel. Past het bij een van onze lopende wervingsopdrachten, dan nemen wij contact met u op voor een kwalificatiegesprek en stellen wij u daarna voor aan de wervende bedrijven.', confidential: 'Uw zoektocht blijft strikt vertrouwelijk: wij delen uw profiel alleen met uw uitdrukkelijke toestemming. Conform de AVG en de DSG kunt u op elk moment de verwijdering van uw gegevens vragen.' },
  },

  /* ── Talent : mandat de recrutement ── */
  talentHiring: {
    fr: { subject: 'Aegryn Talent · Votre mandat de recrutement est enregistré', kicker: 'Mandat enregistré', title: 'Aegryn Talent', intro: 'Nous avons bien reçu votre mandat de recrutement. En voici le récapitulatif :', company: 'Société', role: 'Poste', location: 'Lieu', urgency: 'Urgence', next: 'Notre équipe analyse votre besoin et vous recontacte pour un appel de qualification, puis la définition du profil cible, la recherche et la présentation de candidats présélectionnés.', confidential: 'Votre mandat reste confidentiel : nous ne contactons que des candidats pré-qualifiés et ne divulguons votre identité qu’avec votre accord.', urgency_immediate: 'Immédiate', urgency_month: 'Sous un mois', urgency_quarter: 'Sous un trimestre', urgency_flexible: 'Flexible' },
    en: { subject: 'Aegryn Talent · Your recruitment mandate is registered', kicker: 'Mandate registered', title: 'Aegryn Talent', intro: 'We have received your recruitment mandate. Here is a summary:', company: 'Company', role: 'Role', location: 'Location', urgency: 'Urgency', next: 'Our team is analysing your need and will call you back for a qualification call, then define the target profile, search and present pre-screened candidates.', confidential: 'Your mandate remains confidential: we only contact pre-qualified candidates and disclose your identity only with your consent.', urgency_immediate: 'Immediate', urgency_month: 'Within a month', urgency_quarter: 'Within a quarter', urgency_flexible: 'Flexible' },
    de: { subject: 'Aegryn Talent · Ihr Rekrutierungsmandat ist erfasst', kicker: 'Mandat erfasst', title: 'Aegryn Talent', intro: 'Wir haben Ihr Rekrutierungsmandat erhalten. Hier die Zusammenfassung:', company: 'Unternehmen', role: 'Position', location: 'Standort', urgency: 'Dringlichkeit', next: 'Unser Team analysiert Ihren Bedarf und meldet sich für ein Qualifikationsgespräch, danach folgen Zielprofil, Suche und Vorstellung vorselektierter Kandidaten.', confidential: 'Ihr Mandat bleibt vertraulich: Wir kontaktieren nur vorqualifizierte Kandidaten und geben Ihre Identität nur mit Ihrer Zustimmung preis.', urgency_immediate: 'Sofort', urgency_month: 'Innerhalb eines Monats', urgency_quarter: 'Innerhalb eines Quartals', urgency_flexible: 'Flexibel' },
    it: { subject: 'Aegryn Talent · Il vostro mandato di ricerca è registrato', kicker: 'Mandato registrato', title: 'Aegryn Talent', intro: 'Abbiamo ricevuto il vostro mandato di ricerca. Ecco il riepilogo:', company: 'Società', role: 'Posizione', location: 'Sede', urgency: 'Urgenza', next: 'Il nostro team analizza la vostra esigenza e vi ricontatta per una chiamata di qualifica, poi la definizione del profilo target, la ricerca e la presentazione di candidati preselezionati.', confidential: 'Il vostro mandato resta riservato: contattiamo solo candidati pre-qualificati e riveliamo la vostra identità solo con il vostro consenso.', urgency_immediate: 'Immediata', urgency_month: 'Entro un mese', urgency_quarter: 'Entro un trimestre', urgency_flexible: 'Flessibile' },
    es: { subject: 'Aegryn Talent · Su mandato de selección está registrado', kicker: 'Mandato registrado', title: 'Aegryn Talent', intro: 'Hemos recibido su mandato de selección. Este es el resumen:', company: 'Empresa', role: 'Puesto', location: 'Ubicación', urgency: 'Urgencia', next: 'Nuestro equipo analiza su necesidad y le llamará para una llamada de calificación, después la definición del perfil objetivo, la búsqueda y la presentación de candidatos preseleccionados.', confidential: 'Su mandato es confidencial: solo contactamos con candidatos precalificados y solo revelamos su identidad con su consentimiento.', urgency_immediate: 'Inmediata', urgency_month: 'En un mes', urgency_quarter: 'En un trimestre', urgency_flexible: 'Flexible' },
    nl: { subject: 'Aegryn Talent · Uw wervingsopdracht is geregistreerd', kicker: 'Opdracht geregistreerd', title: 'Aegryn Talent', intro: 'Wij hebben uw wervingsopdracht ontvangen. Hier is de samenvatting:', company: 'Bedrijf', role: 'Functie', location: 'Locatie', urgency: 'Urgentie', next: 'Ons team analyseert uw behoefte en belt u terug voor een kwalificatiegesprek, daarna volgen het doelprofiel, de zoektocht en de presentatie van voorgeselecteerde kandidaten.', confidential: 'Uw opdracht blijft vertrouwelijk: wij benaderen alleen voorgekwalificeerde kandidaten en maken uw identiteit alleen bekend met uw toestemming.', urgency_immediate: 'Onmiddellijk', urgency_month: 'Binnen een maand', urgency_quarter: 'Binnen een kwartaal', urgency_flexible: 'Flexibel' },
  },
}

export function ack(form: keyof typeof ACK, lang: string | null | undefined): Record<string, string> {
  const t = ACK[form]
  return t[(lang as Lang) in t ? (lang as Lang) : 'fr']
}
