-- ============================================================
-- Migration 083 : SUPPRIMÉE — aucune correction supplémentaire requise
-- ============================================================
--
-- Audit complet des fonctions plpgsql :
--
-- Migration 064 couvre déjà en SECURITY INVOKER SET search_path = '' :
--   set_updated_at, handle_updated_at, set_profiles_updated_at,
--   set_expert_profiles_updated_at, set_auction_sessions_updated_at,
--   update_auction_lots_updated_at, update_commission_tiers_updated_at,
--   update_invoices_updated_at, trg_fn_catalogue_requests,
--   update_blocks_grading, handle_new_user, fn_audit_transaction_changes,
--   fn_check_invoice_mismatch, sync_auction_nda_signed_at,
--   is_admin, is_asset_seller, rls_auto_enable
--
-- Migration 082 couvre :
--   update_term_sheets_updated_at, update_mandates_updated_at
--
-- Il ne reste aucune fonction plpgsql sans search_path fixé.
-- Cette migration est intentionnellement vide (placeholder).
-- ============================================================

-- (intentionnellement vide)
